<?php include('assets/header.php'); ?>
<section class="mb-5">
  <h2>O que é RPG (Roleplaying Game)</h2>
  <p>Hoje em dia é muito fácil saber o que significa RPG basta pesquisar na internet, mas em meado dos anos 90, essa possibilidade não existia e a divulgação era algo totalmente no “boca a boca”. Nascido em 1974, nos EUA, uma nova forma de lazer, um jogo que instigava a imaginação e a criatividade, que daí então, não parou de ganhar adeptos. Legiões de jovens, adolescentes e adultos, que escolheram esse tipo de divertimento, passaram a contar histórias, onde cada participante vivia uma história, sem ter que se preocupar em obedecer a uma posição apenas passiva, sendo parte eles mesmos os atores e roteirista, de uma peça teatral que ainda não havia sido concluída.</p>
  <h2>Como funciona uma partida de RPG?</h2>
  <p>Um RPG ou Jogo de Representação, é um jogo onde cada participante faz o papel de um personagem, tomando parte em uma aventura imaginária. O tipo da aventura é definido por um árbitro chamado Mestre (GAME MASTER ou, abreviadamente, GM). O Mestre define o cenário e faz o papel dos “NPCs” (non-player character), ou simplesmente, um personagem não jogável que os personagens encontrarão durante sua aventura.</p>
  <p>Não há necessidade de tabuleiro para os RPG (apesar de alguns sistemas, incluírem regras opcionais de combate em tabuleiro).</p>
  <p>O RPG é jogado verbalmente. O Mestre descreve a situação e diz aos jogadores o que seus personagens veem e ouvem. Os jogadores então descrevem o que eles estão fazendo para vencer o desafio. O Mestre descreve o resultado conseguido com estas ações... e assim por diante. Dependendo da situação, o Mestre pode decidir arbitrariamente o que acontece (com o objetivo de conseguir a melhor aventura), fazendo referência a uma regra específica do jogo (para decidir o que é possível), ou jogando dados (para conseguir um resultado aleatório, o que, vez por outra, pode ser interessante).</p>
  <p>Parte do objetivo do RPG é fazer com que o jogador enfrente a situação como seu personagem o faria. Um RPG permite que o jogador faça o papel de um implacável samurai japonês, um padre sensato ou um garoto de rua fazendo clandestinamente sua primeira viagem espacial... ou qualquer outra pessoa. Numa dada situação, cada uma destas pessoas reagiria de maneira diferente, e é este o objetivo do RPG.</p>
  <p>Portanto, um RPG bem jogado ensina cooperação entre os jogadores e amplia seus horizontes. No entanto, ele não é uma coisa puramente educacional. É também uma das mais criativas formas de entretenimento. A maior diferença entre o RPG e as outras formas de diversão é que a maioria delas é passiva, i.e., a audiência se senta e assiste sem tomar parte no processo criativo. No RPG a audiência participa do processo de criação. Enquanto o GM é o principal contador de histórias, os jogadores são responsáveis pela criação de seus personagens. Portanto, se eles quiserem que alguma coisa aconteça na história, então farão com que aconteça, porque são parte integrante dela.</p>
  <p>Enquanto os outros tipos de diversão são produzidos em série para agradar a maior audiência possível, cada aventura de Roleplaying é uma joia distinta, lapidada por aqueles que tomaram parte nela. O GM (ou autor original da aventura) fornece o material bruto, mas o polimento é dado pelos próprios jogadores.</p>
  <p>A outra coisa importante com relação ao RPG é que ele não precisa ser competitivo. Na maioria das situações o grupo terá, ou não, conseguido realizar seu intento conjuntamente, dependendo do quanto eles cooperaram entre si. E, como na vida real, a maior recompensa por ter jogado bem vem na forma de desenvolvimento do personagem. Quanto melhor um jogador representar seu personagem (o julgamento cabe ao GM), mais o personagem ganhará em habilidade.</p>
  <p>Uma aventura pode ter um objetivo definido: salvar a princesa, encontrar um tesouro, deter uma invasão; ou pode ser uma história sem fim, onde os personagens passam de uma aventura a outra. A escolha cabe ao Mestre e aos jogadores. Uma campanha pode durar anos e, nesse tempo, ver a chegada e partida de personagens (e jogadores).</p>
  <p>No fim de tudo o GM e os jogadores terão criado uma história: como os personagens se conheceram, aprenderam a trabalhar em conjunto, encontraram um desafio e o superaram.</p>
</section>
<?php include('assets/footer.php'); ?>
